export const reasons = [
  "scanning f:/ drive",
  "opening random files",
  "checking underwear",
  "performing network scan",
  "intercepting hostile traffic",
  "measuring initial response times",
  "calibrating data profiles",
  "scanning d:/ drive",
  "scanning x:/ drive",
  "compiling results",
  "accessing remote networks",
  "thinking about the universe",
  "pondering the meaning of life",
  "dividing work into agile sprints",
  "calibrating external sensors",
  "providing emergency response",
  "detecting hostile actors",
  "scanning for viruses",
  "checking file access rules",
  "compiling binaries into assembly",
  "requesting resources from mainframe",
  "requesting network access",
  "requesting DNS resolve for hostname",
  "requesting firewall exceptions",
  "accessing firewall settings",
];
